/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Query TypeMap
import '@sanity/client'

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type PageBuilder = null

export type Config = {
  _id: string
  _type: 'config'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  number?: string
  email?: string
  facebook?: string
  instagram?: string
  address?: NavigationLink
  openingHours?: {
    monday?: string
    tuesday?: string
    wednesday?: string
    thursday?: string
    friday?: string
    saturday?: string
    sunday?: string
    cta?: string
  }
  navigationLinks?: Array<
    {
      _key: string
    } & NavigationLink
  >
}

export type NavigationLink = {
  _type: 'navigationLink'
  name?: string
  link?: Link
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type Link = {
  _type: 'link'
  text?: string
  type?: string
  internalLink?: PageReference
  url?: string
  email?: string
  phone?: string
  value?: string
  blank?: boolean
  parameters?: string
  anchor?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  documentTitle?: string
  slug?: Slug
  content?: PageBuilder
  seo?: Seo
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Icon = {
  _type: 'icon'
  name?: string
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | PageBuilder
  | Config
  | NavigationLink
  | PageReference
  | Link
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Icon
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../web/shared/utils/sanity-queries.ts
// Variable: pageQuery
// Query: *[    _type in ["page"] &&    slug.current == $slug  ][0]{    ...,    content[]{      ...,    },    "seo": {      "_type": "seo",      "title": coalesce(seo.title, ""),      "description": coalesce(seo.description,  ""),      "image": seo.image,      "keywords": coalesce(seo.keywords, []),    },  }
export type PageQueryResult = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  documentTitle?: string
  slug?: Slug
  content: null
  seo: {
    _type: 'seo'
    title: string | ''
    description: string | ''
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    keywords: Array<never>
  }
} | null

// Source: ../web/shared/utils/sanity-queries.ts
// Variable: configQuery
// Query: *[_type == "config"]{    ...,    address {      ...,      "link": {   "type": link.type,  "url": select(    link.type == "email" => "mailto:" + link.email,    link.type == "phone" => "tel:" + link.phone,    coalesce(link.url, link.internalLink->slug.current)  ),  "blank": link.blank,  "parameters": link.parameters,  "anchor": link.anchor }    },    navigationLinks[]{      ...,      "link": {   "type": link.type,  "url": select(    link.type == "email" => "mailto:" + link.email,    link.type == "phone" => "tel:" + link.phone,    coalesce(link.url, link.internalLink->slug.current)  ),  "blank": link.blank,  "parameters": link.parameters,  "anchor": link.anchor }    }  }[0]
export type ConfigQueryResult = {
  _id: string
  _type: 'config'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  number?: string
  email?: string
  facebook?: string
  instagram?: string
  address: {
    _type: 'navigationLink'
    name?: string
    link: {
      type: string | null
      url: string | null
      blank: boolean | null
      parameters: string | null
      anchor: string | null
    }
  } | null
  openingHours?: {
    monday?: string
    tuesday?: string
    wednesday?: string
    thursday?: string
    friday?: string
    saturday?: string
    sunday?: string
    cta?: string
  }
  navigationLinks: Array<{
    _key: string
    _type: 'navigationLink'
    name?: string
    link: {
      type: string | null
      url: string | null
      blank: boolean | null
      parameters: string | null
      anchor: string | null
    }
  }> | null
} | null
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[\n    _type in ["page"] &&\n    slug.current == $slug\n  ][0]{\n    ...,\n    content[]{\n      ...,\n    },\n    "seo": {\n      "_type": "seo",\n      "title": coalesce(seo.title, ""),\n      "description": coalesce(seo.description,  ""),\n      "image": seo.image,\n      "keywords": coalesce(seo.keywords, []),\n    },\n  }\n': PageQueryResult
    '\n  *[_type == "config"]{\n    ...,\n    address {\n      ...,\n      "link": { \n  "type": link.type,\n  "url": select(\n    link.type == "email" => "mailto:" + link.email,\n    link.type == "phone" => "tel:" + link.phone,\n    coalesce(link.url, link.internalLink->slug.current)\n  ),\n  "blank": link.blank,\n  "parameters": link.parameters,\n  "anchor": link.anchor\n }\n    },\n    navigationLinks[]{\n      ...,\n      "link": { \n  "type": link.type,\n  "url": select(\n    link.type == "email" => "mailto:" + link.email,\n    link.type == "phone" => "tel:" + link.phone,\n    coalesce(link.url, link.internalLink->slug.current)\n  ),\n  "blank": link.blank,\n  "parameters": link.parameters,\n  "anchor": link.anchor\n }\n    }\n  }[0]\n': ConfigQueryResult
  }
}
